### ISSUE TITLE
HTTP headers are not being passed along to Remix loaders

### ISSUE THREAD

**Issue by megastep** [penx/remix-google-cloud-functions#170]
I am using this project to serve a Remix app via Firebase functions. While developing, I noticed that the remix loader functions in my routes are not receiving the headers from the HTTP requests in the `request` object being passed along.

I tried the example in this project and it is indeed happening. I believe there is something broken or missing in the way the `createRequestHandler()` function deals with this data.

As a test, I added this loader to `root.tsx`:

```js
export async function loader({ request }) {
  console.log("Request: " + JSON.stringify(request));
  return null;
}
```

The request object passed is something like this:

` {"size":0,"follow":20,"compress":true,"counter":0,"highWaterMark":16384,"insecureHTTPParser":false}`

Which is not at all what you'd expect from a Request object (i.e. it is missing the crucial headers). It looks like some kind of configuration object.

This happens with just doing a `npm run dev`  with the example, so it doesn't seem to have much to do with the Firebase emulator...

My workaround for now is to manually add the request headers to the context so I can still access them with my app but this is less than ideal since this is effectively breaking the Remix APIs.

**Comment by penx** [comment]
Hi @megastep, thanks for raising this. 

What version of remix are you on?

I think our integration tests are accessing the request object and are currently running on remix 1.15.0, so I would guess something had changed since then. If you’re able to test in old versions and see if it works, or even narrow down which version it broke in, it would be a great help. 

This adapter is a minor adaptation to the official express adapter so it may be worth checking what changes have been made to the express adapter since then. 

PRs welcome if you manage to figure it out and have time to contribute.

**Comment by megastep** [comment]
I am on version 1.19.3 which I believe is the current version. I started using Remix just a few weeks ago and I'm still pretty new to it.

I'm poking around this adapter to see how it works but you're probably better equipped to know where to look...

**Comment by megastep** [comment]
Also I am seeing this behavior straight from the example in your project, which I believe is using 1.15.0 already.

**Comment by penx** [comment]
Edit: ignore this, I hadn’t seen your second post

I would guess then that if we update our integration tests in this repository, they will fail with the latest version of remix. If so, it would be good to narrow down which version this first broke in. 

I’m not using this adapter for my current project so will be hard to find much time to support right now but it’s definitely something I want to fix. Hopefully I’ll find a free evening soon but any support would be appreciated. 

I can detail what I’m thinking if you have the time?

Mainly 

- Check out this repo
- Install deps and build 
- Run the playwright tests and assert they pass
- Update references to remix 1.15.0 to be 1.19.3 and reinstall dependencies 
- Run playwright tests and assert they fail

**Comment by penx** [comment]
> Also I am seeing this behavior straight from the example in your project, which I believe is using 1.15.0 already.

Ah ok. Probably something I need to look at then. Leave it with me

**Comment by megastep** [comment]
I wonder if there's maybe a discrepancy with the types of Requests objects being handled? I notice that Firebase expects express-style Request objects whereas the `getLoadContext` function is passed a `GcfRequest` and `GcfResponse`, which while similar, is quite different (and incompatible).

**Comment by megastep** [comment]
I am closing this issue as it actually seems to be working as intended. I seemed to have misunderstood the way the Request object is being handled in the loaders, and while the headers are not visible when looking at JSON-ified data of the object, they are still accessible via the `.headers.get()` function. It is just pretty counter-intuitive and confusing and I literally tore my hair out over this for a couple of days. 😅

As a side note you may want to update some of the package dependencies, particularly firebase-tools has a much more usable emulator that I was able to use to track down this in more detail.
